// Stripe Product Configuration for Kingdom AI Bots
// This file will be automatically generated by the create-stripe-products.js script

export interface StripeProduct {
  productId: string;
  priceId: string;
  descriptiveId: string;
  descriptivePriceId: string;
  price: number;
}

export interface StripeProductsConfig {
  bots: Record<string, StripeProduct>;
  addons: Record<string, StripeProduct>;
  bundles: Record<string, StripeProduct>;
}

// Populated with actual Stripe product IDs from create-stripe-products.js script
export const STRIPE_PRODUCTS: StripeProductsConfig = {
  bots: {
    "sales-assistant-bot": {
      "productId": "prod_SmdUAPbwczTYoP",
      "priceId": "price_1Rr4DBGMSZjMrbvlmx3f6Ff5",
      "descriptiveId": "prod_sales_assistant_bot",
      "descriptivePriceId": "price_sales_assistant_bot",
      "price": 299
    },
    "lead-generation-bot": {
      "productId": "prod_SmdUNYTV8c8jiw",
      "priceId": "price_1Rr4DBGMSZjMrbvlKEz9nvLL",
      "descriptiveId": "prod_lead_generation_bot",
      "descriptivePriceId": "price_lead_generation_bot",
      "price": 249
    },
    "onboarding-bot": {
      "productId": "prod_SmdU7fYmepPUtF",
      "priceId": "price_1Rr4DCGMSZjMrbvlPdjQ3il8",
      "descriptiveId": "prod_onboarding_bot",
      "descriptivePriceId": "price_onboarding_bot",
      "price": 199
    },
    "customer-support-bot": {
      "productId": "prod_SmdUwPTKOvwFLx",
      "priceId": "price_1Rr4DCGMSZjMrbvlBau0bxXZ",
      "descriptiveId": "prod_customer_support_bot",
      "descriptivePriceId": "price_customer_support_bot",
      "price": 349
    },
    "faith-bot": {
      "productId": "prod_SmdUFeR8qt5hAh",
      "priceId": "price_1Rr4DDGMSZjMrbvlv2JAtc0z",
      "descriptiveId": "prod_faith_bot",
      "descriptivePriceId": "price_faith_bot",
      "price": 179
    },
    "course-explainer-bot": {
      "productId": "prod_SmdU3AyBGzaaGL",
      "priceId": "price_1Rr4DEGMSZjMrbvlwgEfJtUV",
      "descriptiveId": "prod_course_explainer_bot",
      "descriptivePriceId": "price_course_explainer_bot",
      "price": 279
    },
    "testimonial-bot": {
      "productId": "prod_SmdUkhi3x2cGxt",
      "priceId": "price_1Rr4DEGMSZjMrbvlOjeFSw4T",
      "descriptiveId": "prod_testimonial_bot",
      "descriptivePriceId": "price_testimonial_bot",
      "price": 159
    },
    "job-application-bot": {
      "productId": "prod_SmdUZ7hlEXqnnG",
      "priceId": "price_1Rr4DFGMSZjMrbvld87TE0rm",
      "descriptiveId": "prod_job_application_bot",
      "descriptivePriceId": "price_job_application_bot",
      "price": 229
    },
    "enhanced-sales-bot": {
      "productId": "prod_SmdUrMJ4Et3b7c",
      "priceId": "price_1Rr4DFGMSZjMrbvll0LxXGUJ",
      "descriptiveId": "prod_enhanced_sales_bot",
      "descriptivePriceId": "price_enhanced_sales_bot",
      "price": 399
    },
    "appointment-booking-bot": {
      "productId": "prod_SmdU5lupgc0sjX",
      "priceId": "price_1Rr4DGGMSZjMrbvl5o27I2Xn",
      "descriptiveId": "prod_appointment_booking_bot",
      "descriptivePriceId": "price_appointment_booking_bot",
      "price": 199
    },
    "faq-&-knowledge-base-bot": {
      "productId": "prod_SmdULj64WNVza6",
      "priceId": "price_1Rr4DGGMSZjMrbvlmFwmAN8f",
      "descriptiveId": "prod_faq_knowledge_base_bot",
      "descriptivePriceId": "price_faq_knowledge_base_bot",
      "price": 179
    },
    "event-management-bot": {
      "productId": "prod_SmdUcY9ignSUhV",
      "priceId": "price_1Rr4DHGMSZjMrbvlbfr2GTpZ",
      "descriptiveId": "prod_event_management_bot",
      "descriptivePriceId": "price_event_management_bot",
      "price": 299
    },
    "inventory-management-bot": {
      "productId": "prod_SmdUrURxaaBe8v",
      "priceId": "price_1Rr4DIGMSZjMrbvlbEVzvuNY",
      "descriptiveId": "prod_inventory_management_bot",
      "descriptivePriceId": "price_inventory_management_bot",
      "price": 249
    },
    "social-media-management-bot": {
      "productId": "prod_SmdU8BmM7FJoVf",
      "priceId": "price_1Rr4DIGMSZjMrbvlThy7Vhnu",
      "descriptiveId": "prod_social_media_management_bot",
      "descriptivePriceId": "price_social_media_management_bot",
      "price": 279
    }
  },
  addons: {
    "custom-branding": {
      "productId": "prod_SmdUEM5Jlig5v5",
      "priceId": "price_1Rr4DJGMSZjMrbvlAYfm1x0J",
      "descriptiveId": "prod_custom_branding",
      "descriptivePriceId": "price_custom_branding",
      "price": 50
    },
    "voicebot-integration": {
      "productId": "prod_SmdUkg2lVsFd3u",
      "priceId": "price_1Rr4DJGMSZjMrbvllqkvN8Z5",
      "descriptiveId": "prod_voicebot_integration",
      "descriptivePriceId": "price_voicebot_integration",
      "price": 75
    },
    "dual-tone-toggle": {
      "productId": "prod_SmdUDG1hzZPRD2",
      "priceId": "price_1Rr4DKGMSZjMrbvl3ztaWR0a",
      "descriptiveId": "prod_dual_tone_toggle",
      "descriptivePriceId": "price_dual_tone_toggle",
      "price": 40
    },
    "memory-engine": {
      "productId": "prod_SmdUYDMoQRGsZ7",
      "priceId": "price_1Rr4DKGMSZjMrbvlo4SmXMzz",
      "descriptiveId": "prod_memory_engine",
      "descriptivePriceId": "price_memory_engine",
      "price": 125
    },
    "embed-service": {
      "productId": "prod_SmdU7fQUwFdnN1",
      "priceId": "price_1Rr4DLGMSZjMrbvlpo15FZEJ",
      "descriptiveId": "prod_embed_service",
      "descriptivePriceId": "price_embed_service",
      "price": 60
    },
    "basic-analytics": {
      "productId": "prod_SmdULl5C2pzPJl",
      "priceId": "price_1Rr4DLGMSZjMrbvlmBHmNbgt",
      "descriptiveId": "prod_basic_analytics",
      "descriptivePriceId": "price_basic_analytics",
      "price": 100
    },
    "legal-&-compliance": {
      "productId": "prod_SmdUWOcPiMzTKg",
      "priceId": "price_1Rr4DMGMSZjMrbvl0Zx8cnsb",
      "descriptiveId": "prod_legal_compliance",
      "descriptivePriceId": "price_legal_compliance",
      "price": 30
    },
    "stripe/zapier-setup": {
      "productId": "prod_SmdUq4dHSk6zcJ",
      "priceId": "price_1Rr4DNGMSZjMrbvluOSQ2QtP",
      "descriptiveId": "prod_stripe_zapier_setup",
      "descriptivePriceId": "price_stripe_zapier_setup",
      "price": 125
    }
  },
  bundles: {
    "sales-suite": {
      "productId": "prod_SmdUp3wYM1B73L",
      "priceId": "price_1Rr4DNGMSZjMrbvlfPphrSl4",
      "descriptiveId": "prod_sales_suite",
      "descriptivePriceId": "price_sales_suite",
      "price": 799
    },
    "support-suite": {
      "productId": "prod_SmdUWhHkAmqsrX",
      "priceId": "price_1Rr4DOGMSZjMrbvlx0tQKtXo",
      "descriptiveId": "prod_support_suite",
      "descriptivePriceId": "price_support_suite",
      "price": 549
    },
    "complete-business-suite": {
      "productId": "prod_SmdUa92LwdsylJ",
      "priceId": "price_1Rr4DOGMSZjMrbvlYvFGneIZ",
      "descriptiveId": "prod_complete_business_suite",
      "descriptivePriceId": "price_complete_business_suite",
      "price": 1499
    }
  }
};

// Helper functions for working with Stripe products
export function getBotProduct(botName: string): StripeProduct | null {
  const key = botName.toLowerCase().replace(/\s+/g, '-');
  return STRIPE_PRODUCTS.bots[key] || null;
}

export function getAddonProduct(addonName: string): StripeProduct | null {
  const key = addonName.toLowerCase().replace(/\s+/g, '-');
  return STRIPE_PRODUCTS.addons[key] || null;
}

export function getBundleProduct(bundleName: string): StripeProduct | null {
  const key = bundleName.toLowerCase().replace(/\s+/g, '-');
  return STRIPE_PRODUCTS.bundles[key] || null;
}

export function getAllProductIds(): string[] {
  const allProducts = [
    ...Object.values(STRIPE_PRODUCTS.bots),
    ...Object.values(STRIPE_PRODUCTS.addons),
    ...Object.values(STRIPE_PRODUCTS.bundles)
  ];
  return allProducts.map(product => product.productId);
}

export function getAllPriceIds(): string[] {
  const allProducts = [
    ...Object.values(STRIPE_PRODUCTS.bots),
    ...Object.values(STRIPE_PRODUCTS.addons),
    ...Object.values(STRIPE_PRODUCTS.bundles)
  ];
  return allProducts.map(product => product.priceId);
}

// New helper functions for descriptive IDs
export function getBotByDescriptiveId(descriptiveId: string): StripeProduct | null {
  const allBots = Object.values(STRIPE_PRODUCTS.bots);
  return allBots.find(bot => bot.descriptiveId === descriptiveId) || null;
}

export function getAddonByDescriptiveId(descriptiveId: string): StripeProduct | null {
  const allAddons = Object.values(STRIPE_PRODUCTS.addons);
  return allAddons.find(addon => addon.descriptiveId === descriptiveId) || null;
}

export function getBundleByDescriptiveId(descriptiveId: string): StripeProduct | null {
  const allBundles = Object.values(STRIPE_PRODUCTS.bundles);
  return allBundles.find(bundle => bundle.descriptiveId === descriptiveId) || null;
} 