import React from 'react';
import Navigation from '../components/Navigation';
import Footer from '../components/Footer';
import BackgroundVideo from '../components/BackgroundVideo';

export default function UGCPolicy() {
  return (
    <div className="relative flex size-full min-h-screen flex-col bg-navy dark group/design-root overflow-x-hidden">
      <BackgroundVideo />
      <div className="layout-container flex h-full grow flex-col relative z-10">
        <Navigation />
        
        {/* Hero Section */}
        <section className="px-4 sm:px-6 md:px-8 lg:px-12 xl:px-40 py-12 sm:py-16 md:py-20">
          <div className="max-w-4xl mx-auto text-center">
            <h1 className="text-white text-3xl sm:text-4xl md:text-5xl font-black leading-tight tracking-[-0.033em] mb-6 sm:mb-8">
              User-Generated Content Policy
            </h1>
            <p className="text-white text-base sm:text-lg md:text-xl font-normal leading-relaxed px-4">
              Last Updated: July 2025
            </p>
          </div>
        </section>

        {/* Content Section */}
        <section className="px-4 sm:px-6 md:px-8 lg:px-12 xl:px-40 py-12 sm:py-16 md:py-20 bg-black/30 backdrop-blur-sm">
          <div className="max-w-4xl mx-auto">
            <div className="prose prose-invert max-w-none">
              <div className="text-white space-y-8">
                
                <div>
                  <p className="text-gray-300 text-sm sm:text-base leading-relaxed">
                    Kingdom Collective empowers creators to upload and share content through our services, including Kingdom Studios, Clips, Lens, Circle, and Voice. This User-Generated Content Policy governs all content submitted, uploaded, recorded, or generated by users.
                  </p>
                </div>

                <div>
                  <h2 className="text-white text-xl sm:text-2xl font-bold mb-4">1. What is UGC?</h2>
                  <p className="text-gray-300 text-sm sm:text-base leading-relaxed mb-4">
                    &ldquo;User-Generated Content&rdquo; includes but is not limited to:
                  </p>
                  <ul className="text-gray-300 text-sm sm:text-base leading-relaxed list-disc list-inside space-y-2 ml-4">
                    <li>Uploaded photos, videos, and audio (e.g. in Kingdom Lens or Voice)</li>
                    <li>AI-generated or co-created content</li>
                    <li>Comments, captions, reels, declarations, and public posts</li>
                    <li>Mentorship or community discussions</li>
                  </ul>
                </div>

                <div>
                  <h2 className="text-white text-xl sm:text-2xl font-bold mb-4">2. Your Responsibilities</h2>
                  <p className="text-gray-300 text-sm sm:text-base leading-relaxed mb-4">
                    By submitting content through our platform, you affirm that:
                  </p>
                  <ul className="text-gray-300 text-sm sm:text-base leading-relaxed list-disc list-inside space-y-2 ml-4 mb-4">
                    <li>You own or have rights to the content you upload</li>
                    <li>You have permission for any people, voices, or third-party media shown</li>
                    <li>Your content does not infringe on copyright, privacy, or other rights</li>
                    <li>Your content complies with our Terms of Service and Acceptable Use Policy</li>
                  </ul>
                  <p className="text-gray-300 text-sm sm:text-base leading-relaxed mb-4">
                    You may not upload:
                  </p>
                  <ul className="text-gray-300 text-sm sm:text-base leading-relaxed list-disc list-inside space-y-2 ml-4">
                    <li>Pornographic, hateful, violent, or abusive content</li>
                    <li>Content intended to impersonate others or spread misinformation</li>
                    <li>Unauthorized music, trademarks, or copyrighted material</li>
                    <li>Spiritual content that misrepresents the Bible or exploits Faith Mode deceptively</li>
                  </ul>
                </div>

                <div>
                  <h2 className="text-white text-xl sm:text-2xl font-bold mb-4">3. License Grant</h2>
                  <p className="text-gray-300 text-sm sm:text-base leading-relaxed mb-4">
                    By uploading UGC, you grant Kingdom Collective a non-exclusive, royalty-free license to:
                  </p>
                  <ul className="text-gray-300 text-sm sm:text-base leading-relaxed list-disc list-inside space-y-2 ml-4 mb-4">
                    <li>Host, store, display, and distribute the content as part of our services</li>
                    <li>Use anonymized content to improve our platform (e.g., template suggestions, AI tuning)</li>
                    <li>Showcase select content (with consent) for promotion or inspiration</li>
                  </ul>
                  <p className="text-gray-300 text-sm sm:text-base leading-relaxed">
                    You retain full ownership of your content unless otherwise stated in a signed release.
                  </p>
                </div>

                <div>
                  <h2 className="text-white text-xl sm:text-2xl font-bold mb-4">4. Content Removal</h2>
                  <p className="text-gray-300 text-sm sm:text-base leading-relaxed mb-4">
                    We reserve the right to remove or disable any content at our discretion if it violates our terms, laws, or community guidelines. Repeated offenses may lead to account suspension.
                  </p>
                  <p className="text-gray-300 text-sm sm:text-base leading-relaxed">
                    If you believe your content has been misused or was removed in error, contact us at <a href="mailto:support@kingdomcollective.pro" className="text-kingdom-gold hover:text-kingdom-gold-soft transition-colors duration-200">support@kingdomcollective.pro</a>
                  </p>
                </div>

              </div>
            </div>
          </div>
        </section>

        <Footer />
      </div>
    </div>
  );
} 