# Kingdom Collective Quarterly Audit
# Comprehensive audit every 3 months (Jan, Apr, Jul, Oct)

name: Quarterly Kingdom Audit

on:
  schedule:
    # Run on the 1st of Jan, Apr, Jul, Oct at 9am UTC
    - cron: '0 9 1 1,4,7,10 *'
  workflow_dispatch: # Allow manual trigger

jobs:
  quarterly-audit:
    name: 🔍 Quarterly Kingdom Audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run Security Audit
        run: npm audit --audit-level=moderate
        continue-on-error: true

      - name: Run Lighthouse CI
        run: npm run lighthouse --if-present
        continue-on-error: true

      - name: Run Accessibility Tests
        run: npm run test:a11y --if-present
        continue-on-error: true

      - name: Run Full Test Suite
        run: npm run test:all
        continue-on-error: true

      - name: Check for unused dependencies
        run: npx depcheck
        continue-on-error: true

      - name: Generate Audit Report
        run: |
          echo "# Quarterly Kingdom Audit - $(date +%Y-%m-%d)" > QUARTERLY_AUDIT.md
          echo "" >> QUARTERLY_AUDIT.md
          echo "## Security Scan" >> QUARTERLY_AUDIT.md
          npm audit >> QUARTERLY_AUDIT.md || true
          echo "" >> QUARTERLY_AUDIT.md
          echo "## Test Results" >> QUARTERLY_AUDIT.md
          echo "See workflow logs for detailed test results" >> QUARTERLY_AUDIT.md
          echo "" >> QUARTERLY_AUDIT.md
          echo "## Action Items" >> QUARTERLY_AUDIT.md
          echo "- Review security vulnerabilities" >> QUARTERLY_AUDIT.md
          echo "- Update dependencies" >> QUARTERLY_AUDIT.md
          echo "- Verify performance metrics" >> QUARTERLY_AUDIT.md
          echo "- Check accessibility compliance" >> QUARTERLY_AUDIT.md
          echo "" >> QUARTERLY_AUDIT.md
          echo "**\"Unless the Lord builds the house, the builders labor in vain.\"** - Psalm 127:1" >> QUARTERLY_AUDIT.md

      - name: Upload Audit Report
        uses: actions/upload-artifact@v3
        with:
          name: quarterly-audit-report
          path: QUARTERLY_AUDIT.md
          retention-days: 90

      - name: Create Issue for Review
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: '🔍 Quarterly Kingdom Audit - ' + new Date().toISOString().split('T')[0],
              body: '## Quarterly Audit Completed\n\n' +
                    'The automated quarterly audit has been completed. Please review:\n\n' +
                    '- [ ] Security vulnerabilities\n' +
                    '- [ ] Performance metrics\n' +
                    '- [ ] Accessibility compliance\n' +
                    '- [ ] SEO status\n' +
                    '- [ ] Test coverage\n' +
                    '- [ ] Dependency updates\n\n' +
                    'View the full report in the workflow artifacts.\n\n' +
                    '**\"Unless the Lord builds the house, the builders labor in vain.\"** - Psalm 127:1',
              labels: ['audit', 'maintenance', 'high-priority', 'quarterly-review']
            })

